server:
  port: 9000
  servlet:
    context-path: /market-core
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

integrations:
  cart-service:
    url: http://localhost:9100/market-cart
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000